### ISSUE TITLE
review issue: hyperband formulas and budget param bounds bounds

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#12]
i think we deviated a bit from the paper here, where eta was always between 0 and 1. 
we at least need to check that the formulas are really correct now, a unit test for this would be great, documenting this in a "technical details" section would also be good

**Comment by SebGruber1996** [comment]
eta is the factor by that the budget is increased each stage - so it has to be >1.
https://arxiv.org/pdf/1603.06560.pdf

Currently, I added an assert that checks if eta is an integer bigger or equal 2.
The question is if non-integers should be allowed.

**Comment by SebGruber1996** [comment]
added unit tests for brackets layout and added details section in the documentation giving more information about how to calculate the brackets

**Comment by berndbischl** [comment]
my bad, is mistypd the issue: i meant

i think we deviated a bit from the paper here, where the "budget" param was always between 0 and 1.
we at least need to check that the formulas are really correct now, a unit test for this would be great, documenting this in a "technical details" section would also be good

**Comment by berndbischl** [comment]
> The question is if non-integers should be allowed.

we should allow non-ints too, i think. NB: is this is another issue

**Comment by juliambr** [comment]
There is no restriction in the original paper.
