### ISSUE TITLE
how do we assign the final result

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#15]
we should take the best configuraton from the archive which was evaluated until now. 
even if this used a smaller fidelity parameter
because on higher fidelity levels we might have already overfitted and the evaluation on the test set is "honest"

**Comment by berndbischl** [comment]
this principle should also be documented

**Comment by SebGruber1996** [comment]
This is already builtin in `mlr3tuning` in the form of the `best()` method:

```
library(mlr3hyperband)
library(mlr3)
library(mlr3tuning)
library(mlr3learners)
set.seed(123)
  
# define hyperparameter and budget parameter for tuning with hyperband
params = list(
  ParamInt$new("nrounds", lower = 1, upper = 16, tag = "budget"),
  ParamDbl$new("eta",     lower = 0, upper = 1),
  ParamFct$new("booster", levels = c("gbtree", "gblinear", "dart"))
)
     
inst = TuningInstance$new(
  tsk("iris"),
  lrn("classif.xgboost"),
  rsmp("holdout"),
  msr("classif.ce"),
  ParamSet$new(params),
  term("evals", n_evals = 100000)
)
     
tuner = TunerHyperband$new(eta = 2L)
tuner$tune(inst)

# return best evaluation
tuner$best() 
```

Additionally, I opened a pull request where I implemented the method `pareto_front()` which works similarly but with several measures for multi crit usage.
https://github.com/mlr-org/mlr3tuning/pull/188

**Comment by SebGruber1996** [comment]
I modified the example and added a "return" section in the doc to give information about this
