### ISSUE TITLE
please document propely how the tagging of the fidelity param and throw a proper error message if this is missing

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#17]
of course its create if you can check against this with a very short "assert" but currently the err-msg seems very cryptical if you forget to do thus

**Comment by SebGruber1996** [comment]
replaced the assert with 
```
if (length(budget_id) < 1) {
  stop("No hyperparameter with a 'budget' tag")
} else if (length(budget_id) > 1) {
  stop("More than one hyperparameter with a 'budget' tag")
}
```

**Comment by berndbischl** [comment]
why do you do this assert in tune_internal? 
always assert as early as you can.
you should assert in constructor?

**Comment by berndbischl** [comment]
sebastian said:
das check ich nicht:
im konstruktor haben wir doch noch gar keinen zugriff auf die tuning instance um einen assert zu tätigen, oder wie ist das gemeint?

**Comment by berndbischl** [comment]
you are correct, i overlooked that this has to do with instance.
