### ISSUE TITLE
unit tests for HB

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#2]
i guess we need to somehow export the general tests from mlr3 tuning, or copy them over.

**Comment by berndbischl** [comment]
you should also code some specific tests for HB

**Comment by SebGruber1996** [comment]
I copied some over and adjusted for using a budget and multi crit optionally
also added unit tests for non dominated sorting with hypervolume as tie-breaker
re-open if more unit tests are desired

**Comment by berndbischl** [comment]
i looked at the tests they seem fine for now as a first try
i dislike the copy-paste in helpers.R from mlr3tuning but i also dont know how to avoid this - easily
