### ISSUE TITLE
uni tests are pretty slow

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#28]
thats always annoying if the run for many minutes.
i know that for a tuning package like this it can be hard to generate tests that ran fast.
i rather have slow tests than bad tests or less tests.

but:
can you maybe check if you can (easily) make them run faster?
here are some usual mistakes:
- using large data sets when smaller ones would be ok
- too many iterations in tuning
- suing 10CV when 2CV would be OK
- using CV when Holdout would be ok
etc

**Comment by SebGruber1996** [comment]
the only thing without altering the test structure would be to reduce the upper budget. I'm gonna do that.
but besides that, I don't have any ideas without sacrificing test quality (I tried to do a separate test for every input scenario to make it clear what is broken; I could speed up things a lot by merging scenarios into one test, but if something breaks it will be less clear what caused it)

**Comment by SebGruber1996** [comment]
Reduced upper budget or increased eta on most unit tests.
Afterwards, unit tests finished in 70 sec on my local machine (which is terrible btw.)
commit id: 00bfbac63b3e6a6f409882ad413010f8525ca290

**Comment by berndbischl** [comment]
then fine, it wasnt a biggie anyway
