### ISSUE TITLE
code review my michel

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#32]
@mllg can you maybe do a 1-2h sweep? you dont necessarily have to change stuff, but at least read and open issues

**Comment by mllg** [comment]
```
#' Naturally, hyperband terminates once all of its brackets are evaluated,
#' so a terminator in the tuning instance acts as an upper bound and should be
#' only set to a low value if one is unsure of how long hyperband will take to
#' finish under the given settings.
```
Would it be possible to get a result then?

**Comment by mllg** [comment]
```
#'   Table containing correcter information about the intermediate values
#'   than given by the console logs. It holds the following columns:
```
What was incorrect about the console output?

**Comment by mllg** [comment]
A few lines below:
```r
#'     The console logs about the bracket index are actually false according
#'     to the original hyperband algorithm, which counts down the brackets
#'     and stops after evaluating bracket 0. The true bracket indices are
#'     given in this column.
```
But why do we output incorrect indices printed in the first place?

**Comment by mllg** [comment]
Did a first quick pass. Will do another more in-deepth soonish.

**Comment by mllg** [comment]
```r
      config_max_b = budget_upper/budget_lower
   
      # we add sqrt(machine eps) for stability
      # try this floor(log(8.1 / 0.1)) = 3 (!!!). it should be 4!
      bracket_max = floor(log(config_max_b, eta) + sqrt(.Machine$double.eps))
```

On my machine, the calculation from the example in the comment is 4 :worried: 

OTOH, you really should calculate `floor(log(8.1) - log(0.1))` instead.

**Comment by SebGruber1996** [comment]
Regarding the logs - this was a hard decision for me and I'm still unsure what would be best:
I assumed that most future users will not read the hyperband paper and, so, are unfamiliar with the bracket indexing. Thus, it makes more sense (as it will be a whole less confusing for the naive user) to index brackets in the "natural" way by starting at 1 and finishing at the actual amount of brackets evaluated. I'm very confident that starting by (# brackets -1) and counting down to 0 is not intuitive.
But then we have the issue that we are not in line with the hyperband paper and may confuse users, who actually read the paper. This is why I added the original "correct" indexing of the brackets in the details. But then (and I see this as a major critic point) we confuse users, who may read the details section, but have no interest in the original paper.
To be honest, I don't know how to solve this without anybody being possibly confused by the indices.

**Comment by SebGruber1996** [comment]
> ```r
>       config_max_b = budget_upper/budget_lower
>    
>       # we add sqrt(machine eps) for stability
>       # try this floor(log(8.1 / 0.1)) = 3 (!!!). it should be 4!
>       bracket_max = floor(log(config_max_b, eta) + sqrt(.Machine$double.eps))
> ```
> 
> On my machine, the calculation from the example in the comment is 4 worried
> 
> OTOH, you really should calculate `floor(log(8.1) - log(0.1))` instead.

Try `floor(log(8.1 / 0.1, 3))` instead - we forgot about the base.
I will implement your last line

**Comment by SebGruber1996** [comment]
> ```
> #' Naturally, hyperband terminates once all of its brackets are evaluated,
> #' so a terminator in the tuning instance acts as an upper bound and should be
> #' only set to a low value if one is unsure of how long hyperband will take to
> #' finish under the given settings.
> ```
> 
> Would it be possible to get a result then?

If I recall correctly, we always have finished evaluations stored (even ones on lower budget), so returning the best ones should always be possible as long as at least one config got evaluated

**Comment by juliambr** [comment]
The points Michel raised have been addressed as far as I see, so I think this issue can be closed. 
This comment relates to issue #37.  

> ```
> #' Naturally, hyperband terminates once all of its brackets are evaluated,
> #' so a terminator in the tuning instance acts as an upper bound and should be
> #' only set to a low value if one is unsure of how long hyperband will take to
> #' finish under the given settings.
> ```
> 
> Would it be possible to get a result then?
