### ISSUE TITLE
comments in TunerHyperband$tune_internal

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3hyperband#35]
Some variables should be documented more thoroughly, because it is not clear at first glance what they represent and what their function is.

**Comment by SebGruber1996** [comment]
`B` was the only variable I found that was lacking an explanation. Added the following comment in line 393 of file `TunerHyperband.R`:
```
# 'B' is approximately the used budget of an entire bracket.
# The reference states a single execution of hyperband uses (smax+1) * B
# amount of budget, and with (smax+1) as the amount of brackets follows
# the claim. (smax is 'bracket_max' here)
```
