### ISSUE TITLE
bmr$rr_data not updated if hyperband terminates early

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3hyperband#37]
If hyperband terminates early, then these lines:
https://github.com/mlr-org/mlr3hyperband/blob/256b3566e3e5dc2b1f735be3e8511e9a56300e97/R/TunerHyperband.R#L494-L497
are never reached and `bmr$rr_data` is not augmented, I believe. I have not tested this but it looks like this would happen?

**Comment by SebGruber1996** [comment]
what is the best way to catch the termination of the `eval_batch` method by a terminator?
This would be a possible solution, right?

**Comment by jakob-r** [comment]
outdated, due to bbotk
