### ISSUE TITLE
unit tests show logger output, should be muffled in setup.R

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#39]
bischl@bb-X1-Carbon-5th-home:~/cos/mlr3hyperband (master) $ rtest
Loading mlr3hyperband
Updating documentation for 'mlr3hyperband'
Writing NAMESPACE
Loading mlr3hyperband
Warning: [/home/bischl/cos/mlr3hyperband/R/TunerHyperband.R:306] undocumented R6 method: `initialize`
Warning: [/home/bischl/cos/mlr3hyperband/R/TunerHyperband.R:306] undocumented R6 field: `info`
Warning: [/home/bischl/cos/mlr3hyperband/R/TunerHyperband.R:314] argument `eta` undocumented for R6 method `initialize()`
Warning: [/home/bischl/cos/mlr3hyperband/R/TunerHyperband.R:314] argument `sampler` undocumented for R6 method `initialize()`
Writing NAMESPACE
Testing package 'mlr3hyperband' with testthat
✔ |  OK F W S | Context
✔ |  40       | nds_selection
⠋ |   1       | TunerHyperbandINFO  [23:36:45.637] Amount of brackets to be evaluated = 4,  
INFO  [23:36:45.664] Start evaluation of bracket 1 
INFO  [23:36:45.685] Training 27 configs with budget of 1 for each 
INFO  [23:36:47.798] Training 9 configs with budget of 3 for each 
INFO  [23:36:48.243] Training 3 configs with budget of 9 for each 
INFO  [23:36:48.424] Training 1 configs with budget of 27 for each 
INFO  [23:36:48.512] Start evaluation of bracket 2 
INFO  [23:36:48.519] Training 12 configs with budget of 3 for each 
INFO  [23:36:49.060] Training 4 configs with budget of 9 for each 
INFO  [23:36:49.278] Training 1 configs with budget of 27 for each 
INFO  [23:36:49.371] Start evaluation of bracket 3 
INFO  [23:36:49.379] Training 6 configs with budget of 9 for each 
INFO  [23:36:49.688] Training 2 configs with budget of 27 for each 
INFO  [23:36:49.851] Start evaluation of bracket 4 
INFO  [23:36:49.859] Training 4 configs with budget of 27 for each 
INFO  [23:36:50.120] Done. 
⠋ |  11       | TunerHyperbandINFO  [23:36:50.421] Amount of brackets to be evaluated = 4,  
INFO  [23:36:50.426] Start evaluation of bracket 1 
INFO  [23:36:50.434] Training 8 configs with budget

**Comment by SebGruber1996** [comment]
Done, commit: https://github.com/mlr-org/mlr3hyperband/commit/34fb05862bce26da319a1209eb4b0699bf028f6b
