### ISSUE TITLE
allow initialization with general Sampler from paradox

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#4]

**Comment by berndbischl** [comment]
here is an example why you should not close this too early: at leats documentation for the Sampler is missing

**Comment by berndbischl** [comment]
and: *if* you document this properly
a) I dont need the lengthy example code in the issue here, i think. i dont want to complain toi much about it, an exmple usually never hurts
b) consider adding this to "@examples" for other users

**Comment by berndbischl** [comment]
please add

a) some assert that the sampler exactly contains the same params of the paramset, without the budget.

b) a unit test that assert is there

i dont know i removed the line that the budget param can be in the Sampler and is ignored, in docs.
usually i dont like this. 
not sure whats best here

**Comment by SebGruber1996** [comment]
a) and b) is done

**Comment by juliambr** [comment]
- [ ]  [@examples section has been added for the sampler](https://github.com/mlr-org/mlr3hyperband/blob/500d4fb68c07d610b4fb61643fbf24bae68e71e2/R/TunerHyperband.R#L211)  
- [ ] ["assert that sampler exactly contains params of paramset" ](https://github.com/mlr-org/mlr3hyperband/blob/500d4fb68c07d610b4fb61643fbf24bae68e71e2/R/TunerHyperband.R#L383)
- [ ] unit tests for assert are there

**Comment by jakob-r** [comment]
I think it is done
