### ISSUE TITLE
not sure if HB should have its own logger.

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#40]
i know we discussed this several times. but i suspect at some point this becomes super confusing to the user how to configure this

**Comment by berndbischl** [comment]
at least this would need to be properly document

**Comment by SebGruber1996** [comment]
I still think my previous solution (https://github.com/mlr-org/mlr3hyperband/issues/30#issuecomment-549439409) is not worse than the current state.
By reading your last comment, I realized the logger documentation was outdated and tried to rewrite it.
See this commit: https://github.com/mlr-org/mlr3hyperband/commit/ada593c8b24f91aa55b952192712a3c9a07a121c

**Comment by be-marc** [comment]
We decided that hb uses the `bbotk` logger.
