### ISSUE TITLE
README should be .Rmd

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3hyperband#43]
And run the code that's shown. Otherwise the code will get outdated without getting noticed.

**Comment by SebGruber1996** [comment]
I did as suggested, but somehow 2 macOS runs errored.
This commit broke it: 4abdbfbcead9f6dd15ef9ecf6bab7f0d12706131

**Comment by pat-s** [comment]
Did you look into the builds? You can see that this has nothing to do with the README so you should not be worried about this.

It is a general problem with the `fs` package on R-devel currently. R-devel is unstable and as long as the issue is not related to your changes, you can ignore it.

However, you should still try to attempt to get the build passing and investigate the issues yourself and not just ignore them (in general).

**Comment by jakob-r** [comment]
It should also be updated to all new changes
