### ISSUE TITLE
Option that additional Measures that are not optimized over, but only measured 

### ISSUE THREAD

**Issue by juliambr** [mlr-org/mlr3hyperband#47]
If I pass k > 1 measures to the tuning instance, it gets automatically treated as a multi-objective problem by hyperband with k objectives. 

We eventually want to optimize w.r.t. l < k measures only, but just log another measure. 

Example: For hyperband, we might want to optimize for a performance measure, but log the training time for the configurations to see how the budget parameter influences our actual resource, the training time.

**Comment by jakob-r** [comment]
It is not possible with the actual mlr3tuning/bbotk design. However you can calculate most measures afterwards on the resample results that are stored in the archive.
