### ISSUE TITLE
Hyperband does not work at all

### ISSUE THREAD

**Issue by ThomasWolf0701** [mlr-org/mlr3hyperband#53]
I tried the Hyperband tuner with my current workflow, and while all the other tuners work fine,
The Hyperband tuner gives me the error:
Fehler in private$.optimize(inst) : abstract

tuner = TunerHyperband$new(eta = 2L)
atRF = AutoTuner$new(learnerRF, resampling_opt, measures, param_setRF, evals, tuner)

atXG$train(task)
Fehler in private$.optimize(inst) : abstract

**Comment by jakob-r** [comment]
Please try the most recent git versions of bbotk, mlr3tuning and mlr3hyperband. Everything should work now.
