### ISSUE TITLE
Implement private .assign_result function

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3hyperband#62]
The optimizer class offers an automatic way to assign the result. It just chooses the evaluation that gave the best result. However, for hyperband you might not want to return a result that is based on a lower fidelity.

**Comment by berndbischl** [comment]
> However, for hyperband you might not want to return a result that is based on a lower fidelity.

why? they are all evaluated on the same test data? we decided return whats best there.
note: higher fidelities could also overfit

**Comment by jakob-r** [comment]
Ok. I was not sure if that was intended and if this is the official way how it is done in hyperband.

**Comment by berndbischl** [comment]
not sure if its "official" :)
but we found it reasonable
